export { default as Hero } from './Hero.svelte'
export { default as Section } from './Section.svelte'
export { default as Tags } from './Tags.svelte'
export { default as Button } from './Button.svelte'
export { default as Header } from './layout/Header.svelte'
export { default as Footer } from "./layout/Footer.svelte"
export { default as Email } from "./icons/Email.svelte";
export { default as Github } from "./icons/Github.svelte";
export { default as Linkedin } from "./icons/Linkedin.svelte";
export { default as WhatsApp } from "./icons/WhatsApp.svelte";
export { default as MenuIcon } from "./icons/MenuIcon.svelte"